### ISSUE TITLE
getRewrite return false not allowing permalinks to be reset

### ISSUE THREAD

**Issue by bansay** [tacowordpress/tacowordpress#17]
this commit:
https://github.com/tacowordpress/tacowordpress/commit/b95bebb836a7c934888a5b395ea72b93cec57eb0

is causing issues with Settings -> Permalink resets,

Assigning Alan to look into a workaround and/or fix for taco, as resetting permalinks is not currently working.

**Comment by brianhaveri** [comment]
What unexpectedly happens (or fails to happen) when you regenerate permalinks?

**Comment by a-dg** [comment]
@bansay I have reverted this commit, as it was clearly causing problems. There seems to be somewhat of a deeper issue with rewrites, perhaps only with newer versions of WordPress. So the revert may not solve every issue.

**Comment by a-dg** [comment]
@bansay Actually, it seems that the default might need to be false. There's a condition in WP core, when registering a post type: `false !== $args->rewrite`. If we return null as the default, this condition passes, allowing the post type to be used as the rewrite slug. That *may* be why it was working before. But like I said, switching between null and false didn't seem to solve the whole problem. More testing required.

**Comment by a-dg** [comment]
Fixed in 6836eacf231222a6f385bc487ea40cd5886e25ac
