### ISSUE TITLE
Move Library classes to a separate package

### ISSUE THREAD

**Issue by jasand-pereza** [tacowordpress/tacowordpress#8]

**Comment by a-dg** [comment]
@jasand-pereza @lofiinterstate I consider this to be a high priority. Let's talk.

**Comment by brianhaveri** [comment]
https://github.com/illuminate/support may be a good replacement for many of the Util classes and methods.

**Comment by brianhaveri** [comment]
FYI, since tacowordpress/util is now a dependency of tacowordpress/tacowordpress, I updated the composer.json accordingly. 163dad4
